### ISSUE TITLE
Select UI library and implement it

### ISSUE THREAD

**Issue by sangdth** [rete-academy/dashboard#7]
Please, discuss here for:

- Which UI library should be used in our project.
- If you choose one over another, please provide reason why.

Lưu ý:
`UI` là `User Interface`, nó thường là một thư viện bao gồm nhiều components được làm sẵn theo cùng một style thống nhất, cung cấp cho developer khả năng tuỳ biến nhằm tăng tốc làm việc. Tất nhiên chúng ta hoàn toàn có thể tự xây dựng một thư viện UI riêng nếu thực sự cần.

Tuy nhiên, mình khuyến khích sử dụng một UI library sẵn có vì tính tiện dụng, tiết kiệm tài nguyên và nhân lực. Trong tương lai nếu chúng ta có nhu cầu thực tập cách quản lý một UI lib, ta hoàn toàn có thể làm ở một project riêng và import vào đây sau.

**Comment by techntv** [comment]
Hiện tại em thấy có 2 UI library đáng chú ý là Ant Design và Material UI. Theo em, mình nên dùng Ant Design do thư viện này đã cung cấp đa số React components, đồng thời có hỗ trợ Typescript, i18n ; cộng đồng sử dụng và tài liệu cũng tương đối nhiều, mình có thể tham khảo và tìm hướng giải quyết nhanh gọn hơn; chỉ có 1 điểm trừ là Ant Design khá nặng so với Material UI (~35MB và ~9MB). Nếu mình dùng cho các dự án nhỏ thì mình sử dụng Material UI là hợp lý.

**Comment by sangdth** [comment]
Bên Material anh có cảm tình với project `RMWC.io` hơn Material UI, kiểu anh thấy maintainer bên RMWC nó active hơn và giữ project simple  hơn bên Material UI, họ làm khá tốt. Còn Ant design thì nhìn đẹp hơn nên chắc vì vậy mà nặng hơn. :D Nếu không có gì phản đối anh cũng muốn dùng Material design cho dễ nhìn, già rồi nút bấm phải to to :D

**Comment by techntv** [comment]
Thư viện `RMWC.io` em đẹp với xịn hơn `Material UI`, nhưng sao nó lại không được cộng đồng đánh giá cao vậy anh?

**Comment by techntv** [comment]
Em thấy `RMWC` có nêu ra một số lý do vì sao được tạo ra để thay thế Material UI: 
- The library is heavy or extremely inflexible (crazy api, opinionated styling)
- The library is an opinionated representation of material or it isn't very polished
- The library has been abandoned

**Comment by sangdth** [comment]
Anh có lần gặp problem bên `Material UI`, report issue thì mấy tháng sau maintainer cũng chưa trả lời. Bên `RMWC` thì trả lời sớm hơn. Mọi người không đánh giá cao thường là do họ chỉ nhìn vào stars trên GitHub only, chứ thực sự không dùng và giao tiếp với maintainers.

**Comment by sangdth** [comment]
Close issue này vì mình sẽ tự build UI lib.
